# Generated by Django 4.2.2 on 2023-06-23 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keeper', '0002_alter_book_cover'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookISBN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn_10', models.CharField(blank=True, max_length=10)),
                ('isbn_13', models.CharField(blank=True, max_length=14)),
            ],
        ),
        migrations.AddField('Book', 'isbn', # added this manually 
                            models.OneToOneField(null=True, 
                                                 blank=True, 
                                                 to='keeper.BookISBN', on_delete=models.CASCADE)
        ),
    ]
