# Generated by Django 4.2.2 on 2023-06-23 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keeper', '0003_bookisbn'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keeper.book')),
            ],
        ),
    ]
